replicaCount: 2

image:
  repository: ghcr.io/iagooteroc/kanban-platform
  tag: 224a93220bc523f1dfc464dc84fd539b1419f6d3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: taskflow.local
      paths:
        - path: /
          pathType: Prefix