replicaCount: 2

image:
  repository: ghcr.io/iagooteroc/kanban-platform
  tag: cbfe2375c68540c1a1b66c441af0a4f2af449e11
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: false